### ISSUE TITLE
no such module

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/TrustSDK-iOS#17]
User reported: 

thanks for TrustSDK this is great, want to integrate it in iOS project but got problems like no TrustSDK "no such module", have tried all type of general solution but no luck,

followed this link : https://github.com/TrustWallet/TrustSDK-iOS

please help me how can i integrate it in my project (need steps).

**Comment by vikmeup** [comment]
@alejandro-isaza can you take a look?

**Comment by alejandro-isaza** [comment]
What version of Xcode do you have? You need at least 9.3.

**Comment by rahulvdawewar** [comment]
ABIType - protocol not conform - Equatable ?
Have XCode 9.0 - is there any solution for this 9.0 version.

Thank you @alejandro-isaza @vikmeup

**Comment by rahulvdawewar** [comment]
No problem - will update Xcode - because of current project dependencies.
Thank you @alejandro-isaza @vikmeup .
