### ISSUE TITLE
Member 'init' cannot be used on type 'Address'

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [TrustWallet/TrustSDK-iOS#23]
![hf8z9p](https://user-images.githubusercontent.com/7009886/44716253-73530c80-aac2-11e8-818d-54a731d10f8d.png)

TrustCore (0.2.2)
TrustSDK (0.0.1)

Swift 4

P.S. I think there must be an EthereumAddress. Not an Address.

**Comment by vikmeup** [comment]
Change `Address` => `EthereumAddress`and it should fix the error, make sure you are running latest master
