### ISSUE TITLE
Impossible to verify the signature

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [TrustWallet/TrustSDK-iOS#26]
Good afternoon.

I've tried to verify the signature, but, unfortunately, I couldn't do that (I get 'false').

Signature created by: `Trust.signMessage()`

I've used this approach for verifying: 
```
let hash = Crypto.hash(messageData)
let isValid = Crypto.verify(signature: signed, message: hash, publicKey: myWalletAddress.data(using: .utf8)!)
```

And two more things:
1. signature verification is success on the https://etherscan.io/verifySig
2. signatures, created for the same message on Android and iOS, are different

**Comment by dmitry-kanunnikoff** [comment]
And I don't see recoverPubkeyFrom method in the Crypto.h in my project (but it is there in Git: https://github.com/TrustWallet/trust-core/blob/master/Sources/Crypto.h) - is CocoaPods version so old?

**Comment by dmitry-kanunnikoff** [comment]
Here https://github.com/TrustWallet/trust-core/blob/08cecb0d655df1b3fc250a36a9912bde2ca701a3/Tests/CryptoTests.swift I see `let data = Crypto.recoverPubkey(from: signature, message: hash)!`, but can't invoke `Crypto.recoverPubkey(from, message)` too.

**Comment by vikmeup** [comment]
@dmitry-kanunnikoff make sure you run latest TrustCore lib

**Comment by dmitry-kanunnikoff** [comment]
@vikmeup Just checked:

Using TrezorCrypto (0.0.8)
Using TrustCore (0.2.2)
Using TrustSDK (0.0.1)

**Comment by vikmeup** [comment]
@dmitry-kanunnikoff can and point to the master? we don't always push to cocoapods updated version

**Comment by dmitry-kanunnikoff** [comment]
@vikmeup Could you, please, tell how can I do that? I'm not a Xcode professional, and can add pods only.

**Comment by vikmeup** [comment]
You can just specify in your pod file for each module
```
pod 'TrustCore', :git=>'https://github.com/TrustWallet/trust-core', :branch=> 'master'
```

**Comment by dmitry-kanunnikoff** [comment]
Mm, thank you very much! All works now! The signature's verifying is correct. Your help was really great!
@vikmeup Please, look at the similar issue on Android: https://github.com/TrustWallet/TrustSDK-Android/issues/10
Seems, signature is not ok there.

**Comment by vikmeup** [comment]
@dmitry-kanunnikoff can you message me on telegram: @vikmeup for quicker feedback

**Comment by dmitry-kanunnikoff** [comment]
Thank you very much for your help!
