### ISSUE TITLE
Compile errors ... EthereumTransaction, EthereumAddress

### ISSUE THREAD

**Issue by rednaxus** [trustwallet/TrustSDK-iOS#29]
Hi.... thanks for making this library...

In the example project, I get the following compile errors:

/TrustSDK-iOS/Sources/TrustSDK/Commands/SignTransactionCommand.swift:15:29: Use of undeclared type 'EthereumTransaction'
/TrustSDK-iOS/Sources/TrustSDK/Commands/SignTransactionCommand.swift:30:30: Use of undeclared type 'EthereumTransaction'
/TrustSDK-iOS/Sources/TrustSDK/Commands/SignTransactionCommand.swift:78:48: Use of undeclared type 'EthereumTransaction'
/TrustSDK-iOS/Sources/TrustSDK/ObjCWrapper/TrustSDKObjC.swift:27:27: Use of unresolved identifier 'EthereumTransaction'
/TrustSDK-iOS/Sources/TrustSDK/ObjCWrapper/TrustSDKObjC.swift:31:17: Use of unresolved identifier 'EthereumAddress'
/TrustSDK-iOS/Sources/TrustSDK/ObjCWrapper/TrustSDKObjC.swift:48:65: Use of unresolved identifier 'EthereumAddress'

**Comment by vikmeup** [comment]
I think you need to change from `Address` => `EthereumAddress` and `Transaction` => `EthereumTransaction `

**Comment by rednaxus** [comment]
ok...i guess you mean EthereumAddress => Address, EthereumTransaction => Transaction...

Then i have to change the instantiation:
        let transaction = Transaction(
            //nonce: 0,
            gasPrice: BigInt(gasPrice)!,
            gasLimit: gasLimit,
            to: Address(string: address)!
            //amount: BigInt(amount)!,
            //payload: .none
        )

on line 27 of TrustSDKObjC

...and it compiles and runs, which is better...continuing to test

**Comment by deda9** [comment]
Just update the Podfile 
  ` pod 'TrustSDK', path: '../' ` into ` pod 'TrustSDK' `
