### ISSUE TITLE
Elrond Signing Not Working via TrustSDK

### ISSUE THREAD

**Issue by iampawan** [trustwallet/TrustSDK-iOS#69]
The same thing works fine with TrustWalletCore

**Comment by hewigovens** [comment]
can you share your sample signing input?

**Comment by iampawan** [comment]
```

        let input = ElrondSigningInput.with {
            $0.transaction = ElrondTransactionMessage.with {
                $0.nonce = UInt64(nonce!)
                $0.value = cAmount.stringValue
                $0.sender = fromAddress!
                $0.receiver = toAddress
                $0.gasPrice = 1000000000
                $0.gasLimit = 70000
                $0.data = ""
                $0.chainID = chainId
                $0.version = 1
                
            }
            $0.privateKey = privateKeyData
        }
```

or do you want the json? Althought it is working fine with walletcore

**Comment by hewigovens** [comment]
This is not very helpful, what's the real of value of those variables? what result would you expect (comparing to wallet core)?

**Comment by iampawan** [comment]
For eg 

`{"nonce":3,"value":"1000000000000000","receiver":"erd1f7j9humvsxa7latnhahu5996en8aw8gpj24jse6uxpy4lqntqgyql9c7vq","sender":"erd1g5znpnjs9jtqultyj9enlv5nrsel0e83cv7r3hsyjnv93caxmz5q3zjcdd","gasPrice":1000000000,"gasLimit":70000,"chainID":"1","version":1,"signature":"301243771e36b2d1324752eae251d640208e837fa11a23525b479ee920d37c15e8eac165ffa3e1809a9b39aa14120e6783300ef3d66a03c1c5641b58e3647b0a"}`

This works fine with wallet core

**Comment by hewigovens** [comment]
@iampawan what's error from sdk? Did selected wallet in app match the `sender`? should be `erd1f7j9humvsxa7latnhahu5996en8aw8gpj24jse6uxpy4lqntqgyql9c7vq`

**Comment by hewigovens** [comment]
I reproduced, will debug it soon
