### ISSUE TITLE
Incorrect assign to transaction payload field

### ISSUE THREAD

**Issue by ezykov** [TrustWallet/TrustSDK-iOS#7]
Hi, I have an issue when I try to send transaction with a "payload" field. For Example, when I send transaction with some data to TrustWallet:
``` swift 
var transaction = Transaction(gasPrice: BigInt(21), gasLimit: 21000, to: address)
transaction.amount = amount
transaction.payload = Data(hexString: "0x8f834227000000000000000000000000000000005224") //some data

trustSDK.signTransaction(transaction) { [weak self] signedTransaction in
    let alert = UIAlertController(title: "Signed Transaction", message: signedTransaction.hexString, 
        preferredStyle: .alert)
    alert.addAction(.init(title: "OK", style: .default, handler: nil))
    self?.present(alert, animated: true, completion: nil)
}
```
it doesn't display at screen:
![image](https://user-images.githubusercontent.com/2045235/40548294-f9b6155e-603c-11e8-896c-a1b01abdeff2.png)

I think it happened because transaction data is base64 encoded string and TrustWalletSDK can't parse it correctly. If change this code (in source TrustWalletSDK - > TrustWalletSDK.swift -> handleSignTransaction function):
```swift 
 transaction.payload = components.queryParameterValue(for: "data").flatMap({ Data(hexString: $0) })
```
for something like this:
```swift 
let data = components.queryParameterValue(for: "data").flatMap({ String($0) })!
let dataEncoded = Data(base64Encoded: data)!
transaction.payload = dataEncoded
```
now it's work correct:
![image](https://user-images.githubusercontent.com/2045235/40549122-51003d4c-603f-11e8-8445-ea1224bcced9.png)

**Comment by vikmeup** [comment]
@ezykov thanks for finding this issue! I will fix this on our side. 

Since data is always in hex, we don't need to convert into base64 I think

**Comment by vikmeup** [comment]
@ezykov should be fixed on master! Thanks

Can you telegram me: @vikmeup? curious to see what you are working on

**Comment by ezykov** [comment]
Glad to be helpful. Thanks for fix issue. Yes, sure, I’ll contact you soon.
