### ISSUE TITLE
Please help me to get my balance 60 xrp and 34 dollars token this app is like a scam please help me how to get my money back


### ISSUE THREAD

**Issue by camper0305** [trustwallet/TrustSDK-iOS#76]
![Screenshot_20210107-092734_Trust Wallet.jpg](https://user-images.githubusercontent.com/76706553/103858020-06f46900-50d1-11eb-9553-f8209767e166.jpg)

**Comment by camper0305** [comment]
Your wallet isn't good its like a scam you deducted me 20 xrp thats for receiving only myghad!

**Comment by camper0305** [comment]
Really bro

**Comment by camper0305** [comment]
![Screenshot_20210107-103524_Chrome.jpg](https://user-images.githubusercontent.com/76706553/103861818-766d5700-50d7-11eb-9784-605df446ae89.jpg)![Screenshot_20210107-103300_Chrome.jpg](https://user-images.githubusercontent.com/76706553/103861827-78cfb100-50d7-11eb-88a1-47f3db6e74da.jpg)![Screenshot_20210107-100401_Trust Wallet.jpg](https://user-images.githubusercontent.com/76706553/103861835-7b320b00-50d7-11eb-9b71-0c62fd956023.jpg)

**Comment by camper0305** [comment]
![Screenshot_20210107-110034_KuCoin.jpg](https://user-images.githubusercontent.com/76706553/103861943-9a309d00-50d7-11eb-9b28-fdda3dc8ee78.jpg)![Screenshot_20210107-110041_KuCoin.jpg](https://user-images.githubusercontent.com/76706553/103861950-9bfa6080-50d7-11eb-905c-a62fe8b5e993.jpg)

**Comment by camper0305** [comment]
Like seriously thats my assets bro

**Comment by camper0305** [comment]
![Screenshot_20210107-110237_KuCoin.jpg](https://user-images.githubusercontent.com/76706553/103862112-e976cd80-50d7-11eb-8b7c-f4e400250617.jpg)

**Comment by camper0305** [comment]
Bro you will make a goodnprofit

**Comment by camper0305** [comment]
I lost almost 100$ bro

**Comment by camper0305** [comment]
Bro

**Comment by camper0305** [comment]
Salam bro kindly please if you don't mind just give my money bqck

**Comment by hewigovens** [comment]
you need 20 XRP to activate your account, this is defined by XRP network
BTW don't create issue not related to TrustSDK

**Comment by camper0305** [comment]
You deductive  xrp to my wallet I put 60 xrp  in there go open my wallet
wallet


daring wire decade supreme inquiry charge citizen blast rack cheap dirt
beyond


If you are good just give me back my lost assets

**Comment by camper0305** [comment]
> you need 20 XRP to activate your account, this is defined by XRP network
> BTW don't create issue not related to TrustSDK
> 

They already deducted me when I transfer 60 I recieve 40 and  xrp and when I put it in my trading account my xrp gone
