### ISSUE TITLE
Salam Your app is very bad I lost all my money I didn't receive anything would you mind if you give me my money back please

### ISSUE THREAD

**Issue by camper0305** [trustwallet/TrustSDK-iOS#77]
![Screenshot_20210107-103524_Chrome.jpg](https://user-images.githubusercontent.com/76706553/103862333-4ffbeb80-50d8-11eb-9f41-76a421cf141d.jpg)```
![Screenshot_20210107-092734_Trust Wallet.jpg](https://user-images.githubusercontent.com/76706553/103862348-58ecbd00-50d8-11eb-93f6-0560dd9ffbfa.jpg)![Screenshot_20210107-110034_KuCoin.jpg](https://user-images.githubusercontent.com/76706553/103862355-5c804400-50d8-11eb-92d1-efab18ffaf60.jpg)
```

**Comment by hewigovens** [comment]
duplicated with #76

**Comment by camper0305** [comment]
Lol even my xrp it i didn't recieve it wtf this qpp
