### ISSUE TITLE
Sign then Send for Tron network

### ISSUE THREAD

**Issue by trongvuong1902** [trustwallet/TrustSDK-iOS#95]
Coin not supported

**Comment by hewigovens** [comment]
It should work? Can you share your sample code?

**Comment by trongvuong1902** [comment]
let a = TronSigningInput.with{
            $0.transaction = TronTransaction.with{
                $0.triggerSmartContract = TronTriggerSmartContract.with{
                    $0.data = "abc".data(using: .utf8)!
                    $0.contractAddress = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"
                    $0.callValue = 1
                    $0.ownerAddress = "TVmCnJ1Apw42PMJwwMnJwTZn6cfMeicG7M"
                }
            }
        }
        
        TrustSDK.signers.tron.signThenSend(input: a) { result in
            switch result {
            case .success(let hash):
                print(hash)
            case .failure(let error): print(error.localizedDescription)
            }
        }

**Comment by trongvuong1902** [comment]
Please take a look. Thanks @hewigovens
