### ISSUE TITLE
Wallet Connect doesn't work properly for IOS

### ISSUE THREAD

**Issue by anxolin** [TrustWallet/TrustSDK-iOS#98]
**Description**
Although Trust has Wallet connect (nice!), it doesn't work if you close the app.

When the Wallet Trust App is in the background or closed, and you try to use the Dapp, the Dapp will send the transaction to be signed by the wallet. The issue is that if the app is not opened this message is lost. Furthermore, if you open later Trust wallet Dapp on top of not getting the messages sent while it was inactive, it doesn't get any new messages either. 

My best guess is that, once the websocket is broken, it doesn't recover and recreate a new websocket using the topic id.

Other wallets, like Metamask allow the app to be in the background

**How to reproduce**
1. Go to any Dapp, like Uniswap
2. Connect using Wallet Connect
3. Try to swap 2 tokens, see how the transaction is shown in Trust ✅
4. Close the app
5. Open the app, see how the transaction is **NOT shown in Trust** automatically ❌
5. Try to swap 2 tokens again, see how the transaction is **NOT shown in Trust** ❌

**Comment by hewigovens** [comment]
Thanks for reporting, we will improve this

**Comment by anxolin** [comment]
Hei @hewigovens is there an approximate date for fixing this?

**Comment by hewigovens** [comment]
Could you please try latest Trust iOS in App Store ?

**Comment by anxolin** [comment]
I'm afraid it doesn't work. Now it even disconnect from the Dapp when I reopen Trust wallet.

**Comment by ArtemGoryunov** [comment]
For security reason the app closes the wallet connect session if app was closed. No need to close the app when you are working with DApp. App closed I mean it was removed from memory not just entered in the background.

**Comment by anxolin** [comment]
I don't think is how Wallet Connect is intended to be used. The channel is available as long as non of the peers (wallet / dapp) decide to disconnect. You can see how many other apps allow this, and make UX better imo.

Why is more secured? once the user unlock the wallet, it has access to it. So it wouldn't matter if the previous session is used.  However, needing to link the Dapp/Wallet every time is inconvenient for the user.
